### ISSUE TITLE
Special chars don't show correctly

### ISSUE THREAD

**Issue by pabgan** [KeithLRobertson/markdown-viewer#40] opened 2018-06-29 10:56 UTC
Hello.

Thanks for your job.

I have an issue. In my setup, special chars like ñ, á, é, í, ó, ú appear as "Ã¡" or things like that. My files are like:
```
$ file Client\ Release\ Validation.mkd 
Client Release Validation.mkd: UTF-8 Unicode text, with very long lines
```
I used to use those files with https://apps.nextcloud.com/apps/files_markdown and they rendered just fine. Is there any extra config that I am missing?

**Comment by david-sa** [comment] 2018-07-19 01:28
Hi pabgan, 

it is the most recurrent topic on this extension: check #3, #4, #11, #26, #28, #29, #34, #37.
I will expand a little the solution provided in #37 because I made some research after encountering the same problem.

Your plain text .mkd file is encoded under UTF-8, which is the currently the de facto standard for most documents. But if you check which encoding is being use when you load it in the browser (going to *View Page Info* -> tab *General*: *Text Encoding*) you will likely see windows-1252. Why does FF choose this charset?

In a nutshell, some legacy systems omitted declaring the charset and relied on the locale for decoding. The current approach of FF is to guess that locale from the top-level domain (or from the browser UI locale for multi-locale domains like .com). For most locales, the charset is windows-1252. Actually, the old (1999) RFC 2616 [set ISO-8859-1](https://tools.ietf.org/html/rfc2616#section-3.7.1) (almost identical to Windows-1252) as default charset for text media types. The current standard from 2014, RFC 7231, [removed it](https://tools.ietf.org/html/rfc7231#appendix-B). So, even when UTF-8 is the currrent standard, it is not officially considered as such: there is no one, and developers **must** include the charset in both the headers and the `meta` tag.

Falling back on UTF-8 when the charset is not explicity provided would break backwards compatibility with legacy systems. Also, it could encourage the bad practice of omitting the charset for UTF-8 encoded documents and that is actually the behavior which leaded us to the current mess. And why don't autodetect the encoding? Due to the [conflict](https://bugzilla.mozilla.org/show_bug.cgi?id=815551#c4) between autodetection and incremental loading. 

The situation is **different for local documents** (*file:* URL scheme), though. First, there are no headers (and in some cases, like ours, no `meta` tag). Second, one can safely (well, more or less) assume local files to be finite and all bytes available soon. Actually, FF will hopefully be able to [auto-detect UTF-8 at some point this year](https://bugzilla.mozilla.org/show_bug.cgi?id=1071816#c59). Again, this will affect *file:* documents only, for *https:* pages the issue is a [WONTFIX](https://bugzilla.mozilla.org/show_bug.cgi?id=815551#c40)).

Until the patch is available, you have basically two options:

- set an invisible [BOM](https://www.w3.org/International/questions/qa-byte-order-mark) (`U+FEFF`) at the beginning of the .md file as a UTF-8 signature. [Many Microsoft's editors](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) add it when saving text as UTF-8. On Linux, at least for GTK based text editors (Gedit, Xed...) you can try `{Ctrl + Shift + U} + FEFF + Enter` to insert it manually ([source](https://superuser.com/a/174874)). This practice is discouraged and it can lead to [display problems](https://www.w3.org/International/questions/qa-utf8-bom.en).

- set the value of the `intl.charset.fallback.utf8_for_file` preference to `true` in `about:config`. Note that this will force UTF-8 encoding for all documents using a *file:* URL scheme, but I guess for most users that's OK.

If you wonder why the extension doesn't set this last preference automatically, WebExtensions API [doesn't provide direct access to preferences](https://wiki.mozilla.org/WebExtensions/FAQ#Does_the_WebExtensions_API_provide_access_to_preferences.3F). It seems that there is not a single way for the author to set the encoding (read also [this](https://github.com/KeithLRobertson/markdown-viewer/issues/34#issuecomment-389549031)). Actually, this very use case is acknowledged in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1071816#c40). 

@KeithLRobertson I saw in the extension description a reference to the BOM but not to `intl.charset.fallback.utf8_for_file`. It could be useful to provide more detailed instructions (there and also in README.md). The same about the MIME type, as discussed in [#2](https://github.com/KeithLRobertson/markdown-viewer/issues/2#issuecomment-321940542).

**Comment by pabgan** [comment] 2018-07-19 09:31
Thanks, David, for your very comprehensive answer. I searched for an 
open issue like mine, forgot about closed ones. Sorry about that.

The Firefox preference suggestion worked for me. Thanks again. I agree 
with the convenience of mentioning this somewhere more visible if it is 
so commonly asked.

Un saludo.
--
Pablo Ganuza Vidal

**Comment by najamelan** [comment] 2018-08-31 13:19
> If you wonder why the extension doesn't set this last preference automatically, WebExtensions API doesn't provide direct access to preferences.

That may be true, but it should be trivial to insert a `meta` tag with a charset based on a setting (default charset), which could default to utf-8. I don't have time to make a pull request though, sorry.

I wouldn't give much of a dime for myself to set the firefox setting, but I generate markdown documents for non computer savvy users and suggest the use of markdown-viewer. In my case, it doesn't really work if it doesn't work out of the box...

**Comment by KeithLRobertson** [comment] 2018-09-01 16:18
Thank you @david-sa for your excellent answer! utf8_for_file is a great find. I'll see if I can get this info out there.

@najamelan, Inserting a `meta` tag in the HTML would not do any good. The encoding (UTF-8 or otherwise) is relevant only when the byte stream is converted into characters, and that has completed long before the markdown text (already converted to characters) is translated into HTML (characters).

**Comment by KeithLRobertson** [comment] 2018-09-04 05:13
@najamelan 
> In my case, it doesn't really work if it doesn't work out of the box...

Then it doesn't work for your case, and that is unfortunate, but it's not something the extension developers can do anything about. If the WebExtensions API doesn't provide a capability, then a web extension can't very well use that capability (that doesn't exist), can it? Complaining won't change that.

I tried @david-sa 's `intl.charset.fallback.utf8_for_file` config setting, and it worked like a charm for local files! Perhaps if you gave your users step-by-step instructions to follow. It's three steps which aren't hard at all.

In any case, this is a well-known issue which, in recent versions of FF, has a workaround. Closing.

**Closed as completed by KeithLRobertson** 2018-09-04 05:13 UTC
