### ISSUE TITLE
Some files not identified as markdown on some paths

### ISSUE THREAD

**Issue by MarcelMarre** [KeithLRobertson/markdown-viewer#45] opened 2018-09-11 10:06 UTC
I have various files (and obviously I would prefer not to have to post content in order to help reproduce the issue). The problem admittedly looks tricky, because the behaviour is rather odd:
1. On some paths, all .md files are recognised as markdown and rendered nicely.
1. On other paths, some .md files are handled correctly, while others are not (they are displayed as plain text).
1. Copying one of the files displayed as plain text to an “unproblematic” path and opening renders it nicely.

In my setup, the problematic paths are inside Subversion working copies (the project is not using git)

I shall try to identify workarounds and specifics on why some files and paths are problematic and edit this issue. I realise that as it is there's precious little to go on...

**Comment by Cimbali** [comment] 2018-11-23 14:27
Similar problem here (maybe the same?) which comes from the way the file is opened as far as I can tell, rather than paths. If you open the directory in firefox then click the `md` file it doesn't work, no matter how and how many times you refresh.

Try: 

    markdown-viewer$ firefox file://$PWD/README.md
    markdown-viewer$ firefox file://$PWD/    # then click on README.md from the directory view

A workaround is to copy the link to the file (right click > copy link location) from the directory view and to paste the address in the directory bar, instead of clicking the link directly.

Nothing useful appears in the developer console as far as I can tell.

**Comment by MarcelMarre** [comment] 2018-11-26 15:16
Thanks, Cimbali, first tests suggest that this is precisely the issue, and havin ga workaround is plenty for me. In fact, even copying the link from a tab that doesn't render markdown into a new one works, which is quite a speedy workaround. So, thanks again!

**Comment by Cimbali** [comment] 2018-12-08 14:13
I've reproduced this with `.txt` files and a minimal webextension, so it seems to me to be a firefox bug. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1512684

**Comment by KeithLRobertson** [comment] 2018-12-15 20:49
Duplicate of the one I opened 3 months ago.  ;-)
https://bugzilla.mozilla.org/show_bug.cgi?id=1489312
See also issue #43.

Closing as it's a FF bug.

**Closed as completed by KeithLRobertson** 2018-12-15 20:49 UTC
Labels: Firefox bug
