### ISSUE TITLE
Cannot suport UTF-8

### ISSUE THREAD

**Issue by idleGG** [KeithLRobertson/markdown-viewer#29] opened 2018-03-02 09:00 UTC
Markdown-Viewer always open md file as “GBK” charset even the file is written as "UTF-8".

**Comment by KeithLRobertson** [comment] 2018-03-17 21:00
I'm assuming the file doesn't have a BOM which tells the reader it's UTF-8. I would welcome a submission to this open source project that fixes it. I haven't figured out how to do it.

**Comment by KeithLRobertson** [comment] 2018-03-17 21:00
Closing as duplicate of #26

**Closed as completed by KeithLRobertson** 2018-03-17 21:00 UTC
