### ISSUE TITLE
Wrong text encoding

### ISSUE THREAD

**Issue by j86989** [KeithLRobertson/markdown-viewer#28] opened 2018-02-27 12:36 UTC
Firefox sets `Western` text encoding instead of Unicode.

For example some characters on `curl` docs pages are displayed incorrectly when file is open.

Pages are displayed correctly if text encoding is manually changed to Unicode by user.

When page is reloaded, Firefox switches back to `Western` encoding causing improper character display.

There is not byte order mark at the beginning of those files however encoding is properly detected by `file` command.

```bash
$ file curl/README.md
curl/README.md: UTF-8 Unicode text
```

```bash
$ file curl/docs/BINDINGS.md
curl/docs/BINDINGS.md: UTF-8 Unicode text
```

```bash
$ od -xc curl/README.md | head -n 2
0000000    5b21    7563    6c72    6c20    676f    5d6f    6828    7474
          !   [   c   u   r   l       l   o   g   o   ]   (   h   t   t
```

```bash
$ od -xc curl/docs/BINDINGS.md | head -n 2
0000000    696c    6362    7275    206c    6962    646e    6e69    7367
          l   i   b   c   u   r   l       b   i   n   d   i   n   g   s
```

In my opinion, the issue has dramatic impact on user experience.

**Comment by KeithLRobertson** [comment] 2018-03-17 20:56
I agree! I would welcome a submission to this open source project that fixes it. I haven't figured out how to do it.

**Comment by KeithLRobertson** [comment] 2018-03-17 20:59
Closing as duplicate of #26

**Closed as completed by KeithLRobertson** 2018-03-17 20:59 UTC
